### ISSUE TITLE
Add mocha and standard into dev dependicies?

### ISSUE THREAD

**Issue by scippio** [node-xmpp/server#141]
I know it's better to have these packages in global place and many devs it has. But I think it will be more easier if there be in the package.json for a dev beginners... :) What you think?

**Comment by sonnyp** [comment]
thanks for the suggestion

The reason it's not in the dependencies is that the node-xmpp projects as several modules and I don't want to have one mocha instance per module.

It's documented https://github.com/node-xmpp/node-xmpp-server#test so I don't think it's an issue.
