### ISSUE TITLE
npm test return "npm ERR! Exit status 7"

### ISSUE THREAD

**Issue by bmg1** [node-xmpp/server#158]
Hi!

Sorry for troubles.
but i can't install node-xmpp-server

- CentOS release 6.7 (Final)
- kernel 2.6.32-573.18.1.el6.x86_64
- node v6.2.0
- npm 3.9.3

* git clone https://github.com/node-xmpp/server.git
* cd server
* npm install
* npm test
 and GET ERRORS:

> # npm test
> 
> > node-xmpp-server@2.1.3 test /var/www/jabber/public_html/server
> > npm run unit && npm run lint && npm run coverage
> 
> 
> > node-xmpp-server@2.1.3 unit /var/www/jabber/public_html/server
> > mocha --recursive test/ -t 3000
> 
> 
> 
>   C2S BOSH server client
>     server
>       1) should listen
>     client
>       2) should connect
> 
>   C2S TCP server client
>     server
>       3) should listen
>     client
>       4) should connect
>       5) should disconnect when server shuts down
> 
>   C2S WebSocket server client
>     server
>       - should listen
>     client
>       - should connect
>       - should disconnect when server shuts down
> 
>   SASL
>     PLAIN
>       6) "before all" hook
> 
>   7) Uncaught error outside test suite
> 
>   0 passing (3s)
>   3 pending
>   7 failing
> 
>   1) C2S BOSH server client server should listen:
>      Uncaught Error: listen EAFNOSUPPORT :::5280
>       at Object.exports._errnoException (util.js:953:11)
>       at exports._exceptionWithHostPort (util.js:976:20)
>       at Server._listen2 (net.js:1240:19)
>       at listen (net.js:1289:10)
>       at net.js:1399:9
>       at _combinedTickCallback (internal/process/next_tick.js:77:11)
>       at process._tickCallback (internal/process/next_tick.js:98:9)
> 
>   2) C2S BOSH server client client should connect:
>      Error: connect ECONNREFUSED 127.0.0.1:5280
>       at Object.exports._errnoException (util.js:953:11)
>       at exports._exceptionWithHostPort (util.js:976:20)
>       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
> 
>   3) C2S TCP server client server should listen:
>      Uncaught Error: listen EAFNOSUPPORT :::5222
>       at Object.exports._errnoException (util.js:953:11)
>       at exports._exceptionWithHostPort (util.js:976:20)
>       at Server._listen2 (net.js:1240:19)
>       at listen (net.js:1289:10)
>       at net.js:1399:9
>       at _combinedTickCallback (internal/process/next_tick.js:77:11)
>       at process._tickCallback (internal/process/next_tick.js:98:9)
> 
>   4) C2S TCP server client client should connect:
>      Error: connect ECONNREFUSED 127.0.0.1:5222
>       at Object.exports._errnoException (util.js:953:11)
>       at exports._exceptionWithHostPort (util.js:976:20)
>       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
> 
>   5) C2S TCP server client client should disconnect when server shuts down:
>      Error: timeout of 3000ms exceeded. Ensure the done() callback is being called in this test.
>   
> 
>   6) SASL PLAIN "before all" hook:
>      Uncaught Error: listen EAFNOSUPPORT :::5222
>       at Object.exports._errnoException (util.js:953:11)
>       at exports._exceptionWithHostPort (util.js:976:20)
>       at Server._listen2 (net.js:1240:19)
>       at listen (net.js:1289:10)
>       at net.js:1399:9
>       at _combinedTickCallback (internal/process/next_tick.js:77:11)
>       at process._tickCallback (internal/process/next_tick.js:98:9)
> 
>   7) SASL PLAIN Uncaught error outside test suite:
>      Uncaught TypeError: Cannot read property 'currentRetry' of undefined
>   
> 
> 
> 
> 
> npm ERR! Linux 2.6.32-573.18.1.el6.x86_64
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "unit"
> npm ERR! node v6.2.0
> npm ERR! npm  v3.9.3
> npm ERR! code ELIFECYCLE
> npm ERR! node-xmpp-server@2.1.3 unit: `mocha --recursive test/ -t 3000`
> npm ERR! Exit status 7
> npm ERR! 
> npm ERR! Failed at the node-xmpp-server@2.1.3 unit script 'mocha --recursive test/ -t 3000'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the node-xmpp-server package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     mocha --recursive test/ -t 3000
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs node-xmpp-server
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls node-xmpp-server
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /var/www/jabber/public_html/server/npm-debug.log
> npm ERR! Test failed.  See above for more details.
> 

Please help where is errors and what need for work test?

Thanks!

**Comment by sonnyp** [comment]
No idea, look around to see why you would get EAFNOSUPPORT errors.

**Comment by bmg1** [comment]
EAFNOSUPPORT - tha say as IPV6 errors

Thanks!

**Comment by sonnyp** [comment]
so what was the issue/fix ?

could help others

**Comment by lloydwatkin** [comment]
The 7 will be a count of the number of fails.
